services:
    # Create directories that store your stacks and store Dockge's stack
    # > mkdir -p /opt/stacks /opt/dockge
    # > cd /opt/dockge
    # > docker compose up -d

    dockge:
        image: louislam/dockge:1
        restart: unless-stopped
        ports:
            - 5001:5001
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/app/data
            # Stacks Directory
            # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
            # ⚠️ 1. FULL path only. No relative path (MUST)
            # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
            - /opt/stacks:/opt/stacks
        environment:
            - TZ=Asia/Kolkata
            # Tell Dockge where to find the stacks
            - DOCKGE_STACKS_DIR=/opt/stacks
        networks:
            ms-private-lobby:
                ipv4_address: 172.27.0.17

    uptime-kuma:
        image: louislam/uptime-kuma:2
        container_name: uptime-kuma
        restart: unless-stopped
        ports:
            - 3001:3001 # This maps the container port "3001" to the host port "3001"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/appdata/uptime-kuma:/app/data # Configuring persistent storage
        environment:
            - TZ=Asia/Kolkata # Set the timezone (change to your preferred local timezone so monitoring times are the same)
            - UMASK=0022 # Set your file permissions manually
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3001"]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 5s
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            ms-private-lobby:
                ipv4_address: 172.27.0.16

networks:
    ms-private-lobby:
        external: true
