services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        hostname: plex
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - VERSION=docker
            - PLEX_CLAIM=${PLEX_CLAIM}
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/appdata/plex/config:/config
            - /tmp/plex_transcode:/transcode
            - /data/media:/data/media:ro # shared media folder
        ports:
            - "32400:32400/tcp"
            - "8324:8324/tcp"
            - "32469:32469/tcp"
            - "1900:1900/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        networks:
            - backend_net
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu, video]
        restart: unless-stopped

    # A python based web application for monitoring, analytics
    # and notifications for Plex Media Server.
    tautulli:
        image: ghcr.io/tautulli/tautulli
        container_name: tautulli
        hostname: tautulli
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/appdata/tautulli:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        ports:
            - 8181:8181
        networks:
            - backend_net
        depends_on:
            - plex

    # New version of Overseer
    seerr:
        image: ghcr.io/seerr-team/seerr:latest
        init: true
        container_name: seerr
        hostname: seerr
        environment:
            - LOG_LEVEL=debug
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/appdata/seerr/config:/app/config
        networks:
            - backend_net
        ports:
            - 5055:5055
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
            start_period: 20s
            timeout: 3s
            interval: 15s
            retries: 3
        restart: unless-stopped
        depends_on:
            - plex

networks:
    backend_net:
        external: true
